### ISSUE TITLE
rtc repository missing

### ISSUE THREAD

**Issue by akarl10** [sfera-labs/strato-pi-kernel-module#1]
in the documentatoin the repository
https://github.com/sfera-labs/rtc-pcf2131
is mentioned. It is missing. Since the i2c address of the rtc clock is not documented there is no easy way to create the dtc by myself

**Comment by giampiero7** [comment]
Hi @akarl10 ,
Just to make sure, you have a Strato Pi CM v3 unit?
You should now be able to see the repo https://github.com/sfera-labs/rtc-pcf2131.

Thanks for your report,
Giampiero

**Comment by akarl10** [comment]
Thank you.

Yes, I have the new one

**Comment by giampiero7** [comment]
Hi @akarl10 ,
Please make sure you have a "SCMB30__" (check the product label), otherwise if it is a "SCMB20__" refer to this user guide:
https://www.sferalabs.cc/files/strato/doc/archive/stratopi-cm/20/stratopi-cm-user-guide.pdf
