### ISSUE TITLE
gpio pin numbering changed in kernel 6.6

### ISSUE THREAD

**Issue by njlaw** [sfera-labs/strato-pi-kernel-module#4]
# Summary

It appears that GPIO pin numbering in kernel 6.6 is now relative to the GPIO controller offset:
 - https://forums.raspberrypi.com/viewtopic.php?t=361116#p2166256

# Environment

```
Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
Strato Pi Model: SPMU30XP
UPS Board FW: 4.3
Raspberry Pi OS: 2024-03-12-raspios-bookworm-armhf-lite.img.xz
```

# Expected Behavior

- strato-pi-kernel-module loads

```
[   13.102451] stratopi: loading out-of-tree module taints kernel.
[   13.128361] stratopi: - | init
[   13.128383] stratopi: - | detecting model...
[   13.128475] stratopi: - | RPi model: Raspberry Pi 3 Model B Plus
[   13.335871] stratopi: - | FW version 4.3
[   13.335909] stratopi: - | model=6
[   13.372128] stratopi: - | ready
```

# Actual Behavior

Model detection fails because GPIO initialization fails.

```
[   13.232560] stratopi: loading out-of-tree module taints kernel.
[   13.233590] stratopi: - | init
[   13.233609] stratopi: - | detecting model...
[   13.233728] stratopi: - | RPi model: Raspberry Pi 3 Model B Plus
[   13.233757] stratopi: * | error detecting model
[   13.233785] stratopi: * | init failed
```

And if a model_num is specified for the module, the soft_uart initialization fails because GPIO initialization fails.

```
[   13.094368] stratopi: loading out-of-tree module taints kernel.
[   13.112289] stratopi: - | init
[   13.112332] stratopi: * | error initializing soft UART
[   13.112361] stratopi: * | init failed
```

I added some additional tracing to `raspberry_soft_uart_init` and the `gpio_request` and `request_irq(gpio_to_irq...` calls were failing.

# Workaround

Adding 512 to all the GPIO pin numbers in module.c seems to work around the issue (on the RPi 3 Model B+):

```c
        } else {
                gpioBuzzer.gpio = 512 + 20;
                gpioWatchdogEnable.gpio = 512 + 6;
                gpioWatchdogHeartbeat.gpio = 512 + 5;
                gpioWatchdogExpired.gpio.gpio = 512 + 12;
                gpioShutdown.gpio = 512 + 16;
                gpioUpsBattery.gpio.gpio = 512 + 26;
                gpioRelay.gpio = 512 + 26;
                GPIO_SOFTSERIAL_TX = 512 + 13;
                GPIO_SOFTSERIAL_RX = 512 + 19;
        }
}
```

I based the 512 on the base of the gpiochip from /sys/class, but I am unfamiliar with the kernel and assume this may vary for different Raspberry Pi models.
```
pi@raspberrypi:~ $ cat /sys/class/gpio/gpiochip512/label
pinctrl-bcm2835
pi@raspberrypi:~ $ cat /sys/class/gpio/gpiochip512/base
512
```

If someone wants to point me in the right direction for a non-workaround fix, I'm happy to open a PR.

**Comment by giampiero7** [comment]
Hi @njlaw ,
Thank you very much for the report.
The issue has been fixed in the last commit.

**Comment by njlaw** [comment]
Hi @giampiero7,

Thank you kindly!  I've confirmed that it works on our SPMU30XP's as of 9e7ae63b4532f163dd8bf4332c060808632f8ec2.
